### ISSUE TITLE
The search does not work if it is minimised.

### ISSUE THREAD

**Issue by b2410** [miguelfreitas/twister-html#374]
If I minimise the window of a search, it is not continued to search in the background any more.

**Not sure:** The construction of my time line works also only if a search window is in the foreground.

**Comment by slr** [comment]
I am sure it *does* continue to search in the background (related part of the code was heavily tuned — and tested — by me in the past July). on the client side we are trying do our best to get the results of requests for hashtags, mentions or DMs (and even cache them). if you get nothing it is because the daemon does not deliver demanded content. so I guess the right place to address the problem is https://github.com/miguelfreitas/twister-html/issues/

about "not sure" note: in case of hashtags only first gotten twists append to board, for all following ones there is the special button with the counter on top of the board (like "23 new posts").

![23 new posts](https://user-images.githubusercontent.com/554015/29635567-d9f6426a-8866-11e7-8239-ba4a4eb0468d.png)

**Comment by slr** [comment]
>  https://github.com/miguelfreitas/twister-html/issues/

sorry, https://github.com/miguelfreitas/twister-core/issues/

**Comment by b2410** [comment]
thank you for the answer and sorry for the spam.
i will post on the right plase.
